breaking: bump terser
stefanpenner/broccoli-concat-analyser pull request #52
Opened 2020-09-16 09:29 UTC by lifeart

2020-09-16 11:09 UTC, lifeart commented
I'm getting different stats in my local and in CI

![image](https://user-images.githubusercontent.com/1360552/93329691-3df2f600-f826-11ea-8c47-5cf37cfe7818.png)

and this is why CI is failing..

2020-09-17 13:44 UTC, rwjblue commented
Generally speaking, all of these things should be separate PRs:

* snapshots need to be changed, to simplify support, tests migrated to jest
* dropped node 6, 8 support
* update terser

I don't have commit/release here, so I'll leave it to @stefanpenner / @simonihmig on how to proceed.

2020-09-17 15:52 UTC, simonihmig commented
@lifeart thanks for working on this!

> Generally speaking, all of these things should be separate PRs:

Generally speaking, I would agree! 😝 Alex, would you mind splitting this up? I guess bumping terser (with the changed test date) would come last, so you can use jest snapshots without having to manually update the text fixtures. At least that's why you wanted to introduce jest here mainly, right?

> I'm getting different stats in my local and in CI

My best *guess* would be that it could be related to line endings, as the numbers are quite close, and only the "raw" numbers diverge. I guess you are running this on Windows, right?

2020-09-17 15:57 UTC, lifeart commented
@rwjblue, @simonihmig thank you for feedback, yeah I think I will try to split it to: jest, node, terser Mr’s

And yes, I’m running tests and snapshots on windows

2020-09-17 19:59 UTC, stefanpenner requested changes

2020-09-17 19:59 UTC, stefanpenner commented on lib/summarize.js
>    return new Promise((resolve, reject) => {
I believe the following is a more concise (with better stack-traces/debugging approach)

```js
async function uglify(content) {
  const { code } = await Tester.minify(content);
  return code;
}
```

2020-09-26 14:17 UTC, lifeart commented
@stefanpenner, @simonihmig 

1.) https://github.com/stefanpenner/broccoli-concat-analyser/pull/53
2.) https://github.com/stefanpenner/broccoli-concat-analyser/pull/54
3.) https://github.com/stefanpenner/broccoli-concat-analyser/pull/55

2020-09-26 14:17 UTC, closed without merging